defaults : &defaults
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: testing_app_development

test: &test
  <<: *defaults
  database: testing_app_test

cucumber:
  <<: *test