defaults : &defaults
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000

development: &DEV
  <<: *defaults
  database: testing_app_development

test: &TEST
  <<: *defaults
  database: testing_app_test
